# Generated by Django 4.2.1 on 2023-08-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Image',
            field=models.ImageField(upload_to='Services'),
        ),
        migrations.AlterField(
            model_name='services',
            name='Updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
