# Generated by Django 4.2.1 on 2023-09-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingCart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductUserRelation',
        ),
    ]
